<?php

namespace Ekreative\AppsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BusinessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IosFolderRepository extends EntityRepository
{

}
